version: "3.8"
services:
  db:
    container_name: book_store
    image: postgres
    environment:
      POSTGRES_DB: "book_store"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book_store
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:changelog-master.xml
    depends_on:
      - db
