version: "3.8"
services:
  db:
    container_name: book_store
    image: postgres
    environment:
      POSTGRES_DB: "book_store"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data
  app:
    container_name: book_app
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./logs/:/usr/local/tomcat/bookstore
