server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://db:5432/book_store
    username: admin
    driver-class-name: org.postgresql.Driver
    password: admin
  liquibase.change-log: classpath:changelog-master.xml
