server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://db:5432/book_store
    username: admin
    driver-class-name: org.postgresql.Driver
    password: admin
  liquibase.change-log: classpath:changelog-master.xml
  mail:
    host: smtp.yandex.ru
    port: 465
    username: 375333113410@ya.ru
    password: ndqhekcmhndmnixj
    sender-address: 375333113410@ya.ru
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    address-update: address.update
